name: "CI: Phase Contract Tests (Advisory)"

on:
  pull_request:
    branches: [main]

jobs:
  contract:
    runs-on: ubuntu-latest
    env:
      ALLY_LIVE: 0
      TZ: UTC
      PYTHONHASHSEED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-tests.txt
      - name: Run phase contract tests
        run: |
          python scripts/run_phase_contracts.py
      - name: Generate phase badges
        run: |
          python scripts/phase_badges.py
      - name: Check coverage gate
        run: |
          coverage report --fail-under=60
      - name: Upload contract test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: contract-test-results
          path: |
            artifacts/ci/junit.xml
            artifacts/ci/coverage.xml
            artifacts/phase_badges.json