name: "CI: Smoke Tests (Required)"

on:
  push:
    branches: [main, 'release/**', 'phase-*', 'chore/**', 'feat/**']
  pull_request:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      ALLY_LIVE: 0
      TZ: UTC
      PYTHONHASHSEED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-tests.txt
      - name: Run smoke tests
        run: |
          pytest -m "smoke and offline and not live" --junitxml=artifacts/ci/smoke-junit.xml | tee artifacts/ci/pytest_stdout.txt
      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results
          path: |
            artifacts/ci/pytest_stdout.txt
            artifacts/ci/smoke-junit.xml
            artifacts/audit_check_ci.json
            artifacts/chat/transcript_ci.jsonl